"""Seed the tweet_queue table with 400 AI-style crypto/tech tweets."""

import os
import sys
import random

# Add parent dir to path so we can import app modules
sys.path.insert(0, os.path.dirname(__file__))

from app.database import SessionLocal, engine, Base
from app.models.tweet import TweetQueue

# Create tables if they don't exist
Base.metadata.create_all(bind=engine)

TWEETS = [
    # --- CRYPTO / WEB3 / DEFI ---
    "Bitcoin doesn't care about your feelings. It just keeps making new highs while everyone waits for a dip.",
    "The best time to buy BTC was 10 years ago. The second best time is when your timeline is panicking.",
    "Ethereum gas fees dropping is the crypto equivalent of finding money in your coat pocket.",
    "Unpopular opinion: 90% of crypto projects are just vibes wrapped in a whitepaper.",
    "DeFi taught me more about finance in 6 months than school did in 16 years.",
    "Staking rewards hitting different when you realize banks give you 0.01% APY.",
    "If you're still explaining crypto to your parents, just wait. They'll ask you about it soon enough.",
    "The crypto market is just a 24/7 global psychology experiment with real money.",
    "Layer 2 solutions are doing what the internet did in the 90s — making things actually usable.",
    "NFTs aren't dead. The hype is dead. The technology is just getting started.",
    "Web3 won't replace Web2 overnight. But it will make you question who owns your data.",
    "The difference between a good crypto project and a scam is about 18 months of patience.",
    "Solana going down used to be a meme. Now it's a feature — they always come back stronger.",
    "Stop checking charts every 5 minutes. Your portfolio doesn't grow faster when you watch it.",
    "Crypto Twitter at 3am hits different. That's where the alpha actually lives.",
    "The real utility of blockchain isn't tokens — it's trustless coordination at global scale.",
    "You don't need to understand every protocol. You need to understand incentive design.",
    "The hardest part of crypto isn't buying. It's holding when everyone says you're wrong.",
    "Decentralized identity is the sleeper use case nobody's pricing in yet.",
    "Zero-knowledge proofs are about to change everything and most people can't explain what they are.",
    "Every bear market produces the next generation of builders. This one is no different.",
    "If your investment thesis fits in a tweet, it's probably not a thesis.",
    "The best crypto wallets are the ones you forget about for 4 years.",
    "Regulatory clarity isn't bullish or bearish — it's just necessary for the next phase.",
    "Bitcoin maxis and ETH maxis arguing while the real alpha is in obscure L2s nobody follows.",
    "The merge happened and nobody's life changed. That's kind of the point of good infrastructure.",
    "Cross-chain bridges are either the future of crypto or the biggest attack vector. Possibly both.",
    "Yield farming in 2024 feels like finding treasure. Yield farming in 2021 felt like printing money.",
    "The people quietly building during bear markets are the ones you'll wish you followed.",
    "Crypto is the only market where retail can front-run institutions if they do the work.",
    "Tokenomics is just economics with extra steps and worse documentation.",
    "DAOs are messy, inefficient, and chaotic. Just like democracy. That's the feature.",
    "Smart contracts are only as smart as the developers who write them.",
    "The next billion crypto users won't know they're using crypto. That's the goal.",
    "Airdrops are the best marketing strategy ever invented. Free money creates lifelong users.",
    "If you can't explain why you bought a token in one sentence, you probably shouldn't have bought it.",
    "Bitcoin's energy consumption debate is tired. The real question is what that energy secures.",
    "Memecoins are the gateway drug to understanding tokenomics and market psychology.",
    "On-chain analytics is the closest thing to a crystal ball in crypto.",
    "The difference between conviction and stubbornness is whether the fundamentals changed.",
    # --- AI / MACHINE LEARNING ---
    "AI isn't coming for your job. Someone who knows how to use AI is coming for your job.",
    "The gap between people who use AI tools and people who don't is growing exponentially.",
    "ChatGPT made everyone an AI expert the way Google made everyone a doctor.",
    "The most underrated AI skill isn't prompting — it's knowing when NOT to use AI.",
    "AI-generated code is like autocomplete on steroids. Still need a human to know what to build.",
    "We're in the age where your AI assistant has better grammar than most humans.",
    "The real AI revolution isn't chatbots — it's AI agents that can actually do things.",
    "Fine-tuning a model is like teaching a genius about your specific problem. Worth the effort.",
    "Open source AI models are democratizing intelligence. That's either exciting or terrifying.",
    "The best AI products don't feel like AI products. They just feel like magic.",
    "Everyone's building AI wrappers. The real moat is proprietary data and distribution.",
    "LLMs are incredibly smart and incredibly stupid at the same time. That's the current state of AI.",
    "Prompt engineering is the new SEO — everyone claims to be an expert, few actually are.",
    "AI hallucinations are just the model being creative without permission.",
    "The companies winning with AI aren't replacing humans — they're giving humans superpowers.",
    "Multimodal AI is where it gets interesting. Text was just the warmup.",
    "Vector databases are the unsung heroes of the AI revolution.",
    "The AI bubble isn't about to pop because this time the technology actually works.",
    "Your competitive advantage in 5 years will be your ability to collaborate with AI systems.",
    "AI safety isn't about Terminator scenarios. It's about bias, misinformation, and job displacement.",
    "The best AI startups solve boring problems exceptionally well.",
    "Running local LLMs on your laptop feels like having a supercomputer from 2020.",
    "AI code review catches bugs I would have shipped. Ego check: appreciated.",
    "Every company is now an AI company. Whether they know it or not.",
    "The irony of AI: it's making us question what makes humans uniquely valuable.",
    "RAG isn't perfect but it's the difference between a chatbot and a knowledge system.",
    "The AI engineer is the new full-stack developer. Know the models, know the infra, ship fast.",
    "Training data is the new oil. Whoever has the best data wins.",
    "AI agents that can browse the web, write code, and manage tasks — we're living in the future.",
    "The cost of intelligence is approaching zero. The cost of wisdom remains infinite.",
    # --- TECH / STARTUPS ---
    "The best startups solve problems so obvious that everyone wonders why nobody did it sooner.",
    "Shipping fast beats shipping perfect. Your users will tell you what perfect looks like.",
    "Technical debt is just a fancy way of saying 'decisions we made when we were desperate.'",
    "The best engineering culture isn't about 10x developers — it's about 10x collaboration.",
    "Startup advice is like horoscopes: vague enough to apply to everyone, specific enough to feel personal.",
    "Your MVP doesn't need to be beautiful. It needs to be useful. Beauty comes with revenue.",
    "The most dangerous phrase in tech: 'We've always done it this way.'",
    "Great products don't need 50 features. They need 3 features that work flawlessly.",
    "Remote work didn't kill culture. Bad management did. Remote just made it visible.",
    "If your startup can be killed by a single API change, you don't have a business — you have a dependency.",
    "The best technical decisions are the ones you can easily reverse.",
    "Developer experience is the new competitive moat. If your tools suck, your talent leaves.",
    "Microservices: the architectural pattern that turns one problem into twelve distributed problems.",
    "Code reviews aren't about finding bugs. They're about sharing knowledge.",
    "The fastest way to kill a startup is to build features nobody asked for.",
    "Good documentation is worth more than good code. Fight me.",
    "Every 'simple' feature request has about 47 edge cases hiding behind it.",
    "Containers solved 'works on my machine.' Now we have 'works in my cluster.'",
    "The best tech stack is the one your team actually knows how to use.",
    "Scaling before product-market fit is like buying a mansion before you have furniture.",
    "Your database schema is your data model is your business model. Choose wisely.",
    "The hardest bug to fix is the one that only happens in production on Fridays at 5pm.",
    "Tech Twitter debates tabs vs spaces while real engineers just use whatever the formatter says.",
    "The best meetings are the ones that could have been a Slack message.",
    "Serverless isn't really serverless — someone else is just managing the servers.",
    "Version control isn't a feature. It's oxygen. If you're not using it, you're suffocating.",
    "The gap between a junior and senior dev isn't code quality — it's knowing what NOT to build.",
    "Pair programming: two people looking at a screen while one types and both learn.",
    "If your API returns 200 OK with an error message in the body, we need to talk.",
    "Monoliths aren't bad. Poorly organized monoliths are bad. Same goes for microservices.",
    "The best architecture is the simplest one that solves the problem.",
    # --- PROGRAMMING / DEVELOPER LIFE ---
    "That feeling when your code works on the first try and you don't trust it at all.",
    "Debugging is just being a detective in a crime movie where you're also the criminal.",
    "The best developers I know read more code than they write.",
    "Programming is 10% writing code and 90% figuring out why the code you wrote doesn't work.",
    "Naming things is hard. Caching things is harder. Cache invalidation is a lifestyle.",
    "The three stages of learning a new framework: excitement, confusion, Stack Overflow.",
    "Every senior developer has a folder of scripts they wrote at 2am that they're afraid to touch.",
    "Git blame should be renamed git understand-the-context.",
    "'It works, don't touch it' is not an engineering principle. It's a prayer.",
    "The best error message is the one that tells you exactly what went wrong and how to fix it.",
    "Comments in code should explain WHY, not WHAT. The code already tells you what.",
    "Refactoring is like cleaning your room. Nobody notices when you do it, everyone notices when you don't.",
    "TypeScript is just JavaScript that went to therapy and learned boundaries.",
    "Every developer has written a TODO comment that will outlive their tenure at the company.",
    "The best way to learn a new language is to build something you actually need.",
    "Copy-pasting from Stack Overflow is a skill. Knowing what to copy-paste is expertise.",
    "Rust developers don't have imposter syndrome because the compiler already made them feel inadequate.",
    "Python: where indentation isn't just style — it's the law.",
    "The real 10x developer is the one who prevents 10 unnecessary features from being built.",
    "Legacy code is just code that makes money and nobody wants to maintain.",
    "Writing tests feels slow until the first time they catch a regression before production.",
    "Docker solved dependency hell by creating orchestration hell. Progress?",
    "The best pull request is the smallest one that still makes sense on its own.",
    "You know you're a developer when you debug your coffee machine's behavior.",
    "Regex: write once, understand never, deploy with anxiety.",
    # --- FINTECH / MARKETS ---
    "Traditional finance moves at the speed of fax machines. DeFi moves at the speed of blocks.",
    "The stock market is just crypto with better PR and slower settlement times.",
    "Fintech companies are just banks with better UIs and worse customer support.",
    "Payment APIs turned every developer into a potential fintech founder.",
    "The biggest innovation in finance isn't AI trading — it's removing friction from payments.",
    "Real-time payments should have been the default 20 years ago. We just accepted the delay.",
    "Banking APIs are the most boring and most important infrastructure being built right now.",
    "The future of finance is programmable money. Everything else is just a better spreadsheet.",
    "Central bank digital currencies are just crypto but with the government watching closer.",
    "Neobanks taught traditional banks that people actually care about UX. Revolutionary concept.",
    # --- PRODUCT / DESIGN ---
    "The best product managers say 'no' more than they say 'yes.'",
    "Good UX is invisible. Bad UX is a tweet thread.",
    "A/B testing is just arguing with data instead of opinions. Highly recommend.",
    "The feature your users are requesting is rarely the feature they actually need.",
    "Design systems are like gym memberships — everyone agrees they're important, few actually use them.",
    "Dark mode isn't a feature. It's a lifestyle choice. And it's the correct one.",
    "The most important button on any page is the one that takes users where they want to go.",
    "Product-market fit feels like surfing. If you have to ask whether you have it, you don't.",
    "Onboarding flows that require more than 3 steps lose 50% of users. And that's generous.",
    "The best feature launches are the ones nobody notices because they just work.",
    # --- CULTURE / TECH PHILOSOPHY ---
    "We normalized reading terms of service we never read. That's wild when you think about it.",
    "The internet gave everyone a voice. Social media gave everyone an audience. AI gives everyone a tool.",
    "Privacy is the luxury good of the digital age. And it shouldn't be.",
    "Screen time reports are the modern equivalent of the bathroom scale. Nobody likes what they see.",
    "Technology is neutral. The people building and using it are not.",
    "The metaverse won't replace reality. But it might make reality feel optional.",
    "Email was supposed to be dead 10 years ago. It's still where important things happen.",
    "Notifications are the tax we pay for connectivity.",
    "Digital minimalism isn't about using less tech. It's about using the right tech intentionally.",
    "Open source is proof that collaboration at scale works. The cathedral can learn from the bazaar.",
    # --- CYBERSECURITY ---
    "Your password is probably in a database breach somewhere. Go check haveibeenpwned right now.",
    "Two-factor authentication isn't optional anymore. It's the seatbelt of the internet.",
    "The weakest link in any security system is the human who clicks 'I agree' without reading.",
    "Cybersecurity is the only field where you get paid to think like a criminal.",
    "A VPN doesn't make you anonymous. It makes you anonymous-ish. Big difference.",
    "Phishing emails are getting so good that even security researchers have to double-check.",
    "Zero trust architecture: trust nobody, verify everything, still get hacked occasionally.",
    "The best security is the kind users don't notice. The worst security is the kind that's annoying.",
    "Bug bounties are just outsourcing security testing to people who are better at it than you.",
    "End-to-end encryption should be the default, not the premium feature.",
    # --- DATA / ANALYTICS ---
    "Data is the new oil, but most companies are still figuring out how to drill.",
    "Dashboards don't make decisions. People make decisions. Dashboards make people feel informed.",
    "The plural of anecdote is not data. But in startups, it's often the best we have.",
    "ETL pipelines are the plumbing of modern business. Nobody cares until they break.",
    "If your data pipeline has more steps than your product's onboarding flow, something's wrong.",
    "Real-time analytics is often solving a problem nobody actually has.",
    "The best data scientists are the ones who can explain their findings to non-technical people.",
    "A/B tests are only as good as the hypotheses behind them.",
    "Most 'big data' problems are actually 'bad data' problems.",
    "SQL is 50 years old and still the most practical skill in tech. Respect.",
    # --- ADDITIONAL CRYPTO ---
    "Bitcoin ETFs changed the game. Wall Street is finally playing by crypto's rules.",
    "The best time to learn about DeFi is when nobody's talking about it.",
    "Stablecoins are the most boring and most useful innovation in crypto.",
    "Crypto exchanges going public is like the rebels joining the empire. Mixed feelings.",
    "Hardware wallets are like smoke detectors. You don't need them until you desperately need them.",
    "The crypto winter wasn't a bug — it was a feature. It filtered out the tourists.",
    "MEV is the dark side of DeFi that most users don't even know exists.",
    "Restaking is either the most capital-efficient innovation or a house of cards. Time will tell.",
    "Privacy coins aren't about hiding from authorities. They're about financial sovereignty.",
    "The best crypto communities are the ones that talk about technology, not price.",
    "Modular blockchains are the Unix philosophy applied to crypto. Do one thing well.",
    "Real World Assets on-chain is boring tech with trillion-dollar potential.",
    "Account abstraction will do for crypto UX what the iPhone did for mobile.",
    "Governance tokens with no real governance power are just collectibles with extra steps.",
    "Crypto lending protocols learned the hard way that leverage cuts both ways.",
    "The next crypto cycle will be driven by utility, not speculation. At least that's the hope.",
    "Inscriptions proved that every blockchain will eventually be used for things its creators never intended.",
    "Bitcoin's halving cycles are the most predictable macro events in any market. Use that.",
    "Cross-chain interoperability is the internet moment for crypto. We're building the TCP/IP layer.",
    "The biggest risk in crypto isn't volatility — it's smart contract bugs.",
    # --- ADDITIONAL AI ---
    "GPT wrappers raised millions. The ones with actual moats raised billions.",
    "Synthetic data generation might solve the data scarcity problem. Or create a new kind of bias.",
    "The AI music debate is just the photography vs painting debate of the 21st century.",
    "Embedding models are the quiet workhorses behind every AI-powered search feature.",
    "The day AI can reliably do my taxes is the day I become a true believer.",
    "RLHF is how we teach AI to be polite. The jury's still out on whether that's enough.",
    "Edge AI means your phone is about to get a lot smarter without sending data to the cloud.",
    "The best use of AI I've seen is mundane: auto-categorizing expenses. Boring but life-changing.",
    "Foundation models are the new platforms. Build on them or get built over.",
    "AI art generators didn't kill art. They just made everyone realize they can't art-direct either.",
    "Computer vision in retail is creepy until it means no checkout lines. Then it's innovation.",
    "The AI hype cycle is real but so is the technology. Both things can be true.",
    "Autonomous agents are the next frontier. We're going from AI that answers to AI that acts.",
    "The context window is the new RAM. Bigger isn't always better but it sure helps.",
    "Small language models running locally will be bigger than massive models in the cloud.",
    "Few-shot learning is basically teaching AI by example. Turns out that works for machines too.",
    "AI-powered code completion saved me 2 hours today. That's 10 hours a week. That's a revolution.",
    "The ethical AI debate won't be settled by ethicists alone. It needs engineers at the table.",
    "Mixture of experts models are just team management applied to neural networks.",
    "AI winter isn't coming because this time we have products people actually use every day.",
    # --- ADDITIONAL TECH/STARTUPS ---
    "The best time to start a company was when nobody else believed in the idea.",
    "Burn rate anxiety is the universal startup experience nobody prepares you for.",
    "Product-led growth is just making something so good that marketing becomes optional.",
    "Your tech stack doesn't matter if nobody uses your product.",
    "The real moat is speed of execution, not the idea itself.",
    "B2B SaaS is just solving spreadsheet problems one at a time.",
    "Indie hackers building profitable businesses with $0 in funding is the best flex in tech.",
    "The best career advice in tech: learn to write. Not code — English. Communication is everything.",
    "APIs are eating the world faster than software ever did.",
    "Every startup claims to use AI now. Most of them have an if-else statement.",
    "Kubernetes is amazing when you need it and overkill when you don't. Most don't need it.",
    "The cloud was supposed to save money. My AWS bill suggests otherwise.",
    "Observability isn't monitoring. Monitoring tells you something's wrong. Observability tells you why.",
    "Feature flags are the undo button for production. Use them.",
    "CI/CD isn't a tool — it's a culture. If your deploys are scary, that's a culture problem.",
    "GraphQL solved overfetching. It also introduced a whole new category of complexity.",
    "WebAssembly is about to make the browser the universal runtime. Again.",
    "The best tech talks are the ones where someone admits they messed up and explains what they learned.",
    "Platform engineering is just DevOps with a product mindset. And it's working.",
    "Your monitoring dashboard having more alerts than your app has users is a red flag.",
    # --- ADDITIONAL PROGRAMMING ---
    "Functional programming is like eating vegetables. You know it's good for you but OOP tastes better.",
    "The best code is the code that doesn't exist. Every line is a liability.",
    "JSON won the data format wars not by being the best, but by being the most convenient.",
    "Technical interviews should test problem-solving, not memorized algorithms from 1965.",
    "Hot take: most design patterns are just workarounds for language limitations.",
    "The joy of deleting code is underrated. Subtraction is often better than addition.",
    "Markdown is the most successful markup language because it stays out of your way.",
    "Every framework has a 'getting started' guide that takes 5 minutes and a 'real project' phase that takes 5 months.",
    "The best debugging tool is a good night's sleep. The second best is console.log.",
    "Go's simplicity is its superpower. Not having generics for years was frustrating but clarifying.",
    "API versioning: the problem everyone agrees needs solving but nobody agrees on how.",
    "SSH into production to fix a bug at 2am is a rite of passage every developer shares.",
    "The only thing worse than no documentation is wrong documentation.",
    "Environment variables: the glue holding every deployed application together with hope.",
    "Vim users don't use Vim because it's efficient. They use it because quitting isn't an option.",
    # --- ADDITIONAL MARKETS/FINTECH ---
    "The stock market doesn't reward intelligence. It rewards discipline and patience.",
    "Options trading is just betting with extra math.",
    "Index funds are the cheat code of investing. Nobody wants to hear it but it's true.",
    "Robo-advisors: teaching people that boring diversified portfolios beat stock picking since 1975.",
    "Buy now, pay later is just layaway with better marketing and a tech valuation.",
    "Embedded finance means every company is becoming a fintech company whether they like it or not.",
    "The best financial advice fits in a tweet: spend less than you earn, invest the rest, be patient.",
    "Prop trading firms hiring 22-year-olds to manage algorithms is peak 21st century.",
    "Real estate tokenization could make property investing accessible. If regulations catch up.",
    "The irony of trading apps: designed to make investing easy, gamified to make it addictive.",
    # --- ADDITIONAL CULTURE ---
    "The attention economy's biggest product is anxiety. We're all power users.",
    "Reply guys are the comment section that learned to walk.",
    "The algorithm doesn't know what you like. It knows what keeps you scrolling. Different things.",
    "Building in public is just journaling with peer pressure and accountability.",
    "Tech conferences are 10% learning, 20% networking, and 70% collecting stickers.",
    "The best tech communities are the ones where asking 'dumb' questions is encouraged.",
    "Newsletter fatigue is real. We went from email hell to curated email hell.",
    "Podcast episodes over 2 hours assume I have a commute I definitely don't have anymore.",
    "The tech industry's obsession with disruption created the most disrupted workforce in history.",
    "Side projects are where good developers become great developers. Ship something for fun.",
    # --- ADDITIONAL SECURITY ---
    "Supply chain attacks are the new zero-days. You're only as secure as your dependencies.",
    "Biometric authentication sounds futuristic until someone 3D-prints your fingerprint.",
    "Security through obscurity is like hiding your house key under the doormat. Everyone knows.",
    "The best incident response plan is the one you practiced before the incident.",
    "Password managers are the most boring security improvement with the highest impact.",
    "Deepfakes in video calls are going to make trust the most valuable commodity.",
    "API security is often an afterthought. That's exactly why it's the most common attack vector.",
    "The CISO's job is basically being a professional pessimist who's always right eventually.",
    "Pen testers are the only people who get congratulated for breaking things.",
    "Security awareness training that nobody takes seriously is still better than no training at all.",
    # --- ADDITIONAL DATA ---
    "Data mesh is just microservices for data. With all the same coordination headaches.",
    "The best data architecture is the one that makes data accessible without making it chaotic.",
    "Feature stores are the bridge between data engineering and ML engineering nobody knew they needed.",
    "PostgreSQL is the Swiss Army knife of databases. It does everything reasonably well.",
    "Data quality issues cost companies millions. But nobody wants to fund the team that fixes them.",
    "The modern data stack has more tools than a hardware store. Simplify.",
    "Streaming vs batch processing: it depends on whether your business moves at minutes or hours.",
    "dbt transformed how we think about data transformation. SQL isn't dead, it just leveled up.",
    "Data governance sounds boring until a privacy violation costs you a headline.",
    "The best analytics are the ones that change someone's mind. Everything else is decoration.",
    # --- HOT TAKES / SPICY ---
    "Unpopular opinion: most blockchain use cases work better with a regular database.",
    "The metaverse pivot was the corporate equivalent of a midlife crisis sports car.",
    "Crypto influencers with 100k followers and 3 months of experience are the WebMD of finance.",
    "The only thing more overrated than hustle culture is the backlash against hustle culture.",
    "If your company's tech blog only posts engineering updates, nobody outside the company reads it.",
    "Hot take: the best programming language is the one that ships your product.",
    "LinkedIn thought leaders are just astrology for MBAs.",
    "The silicon in Silicon Valley matters less every year. The network effects are what remain.",
    "Pivoting isn't failure — it's product-market fit by trial and error.",
    "Unpopular opinion: Slack channels are just meetings that nobody can leave.",
    "The blockchain trilemma is just the project management triangle in a trenchcoat.",
    "Most Web3 apps have a Web2 experience with extra wallet pop-ups.",
    "The crypto industry's relationship with regulation is like a teenager's relationship with curfew.",
    "Cloud certifications are just tech scouts badges for adults. Still worth getting.",
    "The best investment in tech isn't a stock — it's learning to code.",
    "If you're building with AI and not thinking about edge cases, you're building a PR crisis.",
    "The attention span of the average crypto investor is about one market cycle.",
    "Tech debt is just past decisions haunting present developers.",
    "Every developer secretly believes their code is beautiful and everyone else's is spaghetti.",
    "Blockchain gaming promised play-to-earn but delivered pay-to-maybe-earn.",
    # --- EXTRA CRYPTO ALPHA ---
    "The DeFi protocols that survive three bear markets are the ones worth your attention.",
    "On-chain derivatives are where TradFi meets DeFi and neither side is fully ready.",
    "Liquid staking unlocked $40B in capital that was just sitting there. That's efficiency.",
    "The next exchange to go down will be the one that said 'trust us' the loudest.",
    "Crypto portfolio management: 80% doing nothing, 15% researching, 5% actually trading.",
    "Layer 3s are coming and I'm not sure we even finished figuring out Layer 2s.",
    "The memecoin-to-utility pipeline is real. Some of the best communities started as jokes.",
    "Token launches on day one are for degens. Token accumulation in month six is for strategists.",
    "Whale watching on-chain is the financial equivalent of birdwatching. Equally nerdy, more profitable.",
    "The best crypto analyst is your own on-chain research. Influencer takes are free for a reason.",
    # --- EXTRA AI PRACTICAL ---
    "AI meeting summaries are saving me 5 hours a week. The future is now and it takes notes.",
    "Cursor changed how I code. Not because it writes code for me — because it removes friction.",
    "The best use of AI in business isn't content generation — it's process automation nobody sees.",
    "Voice AI is about to make every phone tree obsolete. Customer support will never be the same.",
    "AI-powered search is killing the 10 blue links. You'll get answers, not websites.",
    "Building AI features without user feedback loops is like driving blindfolded. Add telemetry.",
    "The model doesn't need to be perfect. It needs to be better than the current process.",
    "Retrieval-Augmented Generation turned chatbots from toys into enterprise tools overnight.",
    "Fine-tuning vs prompting: know when your problem needs a scalpel and when it needs a hammer.",
    "The best AI demos don't show what AI can do — they show what humans couldn't do before.",
    # --- EXTRA TECH WISDOM ---
    "Ship weekly. Demo monthly. Reflect quarterly. The rhythm matters more than the speed.",
    "The companies that win aren't the ones with the most engineers. They're the ones with the clearest priorities.",
    "Premature optimization is the root of all evil. But so is premature abstraction.",
    "Your users don't care about your architecture. They care about whether the button works.",
    "The best engineering managers protect their team's focus like it's a finite resource. Because it is.",
    "Every 'urgent' bug is a failure in testing, monitoring, or expectations. Fix the system, not just the bug.",
    "The best standup is under 10 minutes. If it's longer, it's a planning meeting pretending to be agile.",
    "Burnout in tech isn't about working too hard. It's about working hard on things that don't matter.",
    "The senior engineer's secret: knowing which corners to cut and which to protect.",
    "Your code doesn't need to be clever. It needs to be clear. Clever code is a bug waiting to happen.",
    "Migrations are the scariest thing in engineering. Everything else is just syntax.",
    "The right tool for the job isn't the newest tool — it's the one your team can debug at 3am.",
    "Framework fatigue is real. Pick one, learn it deeply, and stop chasing the new hotness.",
    "Open source maintainers are the most underappreciated people in tech. Buy them a coffee.",
    "Technical writing is a superpower. The engineer who can explain complex things simply wins every time.",
    "Incident post-mortems without action items are just group therapy sessions.",
    "The cost of a meeting is (number of people) x (their hourly rate) x (meeting length). Do the math.",
    "Backwards compatibility is a promise to your users. Breaking it is breaking trust.",
    "Logs, metrics, traces — pick two, debug the third. Observability is a three-legged stool.",
    "The best code review comment is a question, not a command.",
    # --- ROUND OUT TO 400 ---
    "Self-custody in crypto is like home security — annoying until the one time it saves everything.",
    "The real alpha in crypto is reading the GitHub commits, not the price charts.",
    "AI-generated podcasts are coming. Prepare for your drive to get weirder.",
    "Every token has a community. Not every community has a viable token. Know the difference.",
    "DevOps isn't a role. It's a philosophy. And most companies still don't get it.",
    "The GPU shortage is just the new chip shortage wearing a different hat.",
    "Crypto whitepapers should come with a TLDR. Nobody's reading 47 pages of game theory.",
    "Blockchain oracles are the unsung heroes connecting on-chain and off-chain worlds.",
    "Your landing page has 3 seconds to explain what you do. Most waste 2 on a hero animation.",
    "The future of work isn't remote vs office. It's async vs sync. And async is winning.",
    "NFT royalties being optional now proves that code is law until someone changes the code.",
    "The best developers are lazy in the right way — they automate everything they do twice.",
    "AI isn't replacing designers. It's replacing the 47 iterations before the designer says 'that one.'",
    "Crypto taxes are the final boss that nobody prepared for.",
    "The best startup pitch isn't a deck — it's a demo that makes investors forget they had questions.",
    "Machine learning models degrade over time. If you're not retraining, you're slowly breaking.",
    "Decentralized social media sounds great until you realize moderation is the hard part.",
    "Every great tech company was once a terrible idea that happened to work.",
    "Protocol-level thinking is the meta-skill of Web3. Think in systems, not features.",
    "Your deployment pipeline is a product. Treat it like one.",
    "AI replacing search is like streaming replacing cable. Slowly, then suddenly.",
    "Crypto portfolio diversification doesn't mean 12 different dog coins.",
    "The best system design is the one the whole team can whiteboard from memory.",
    "Infrastructure as code is just git for your servers. Should've been obvious.",
    "Minting on mainnet during high gas fees is the crypto equivalent of grocery shopping when hungry.",
    "Technical leadership isn't about having all the answers. It's about asking the right questions.",
    "The gap between AI demo and AI product is about 6 months of edge case handling.",
    "DeFi yield is just compensation for risk. If you can't identify the risk, you ARE the risk.",
    "Your CI pipeline running for 45 minutes means 45 minutes of context switching. Fix it.",
    "Tokenized treasury bills are the trojan horse that brings institutions into DeFi.",
    "Every great codebase started as a terrible prototype someone had the courage to ship.",
    "AI-first companies aren't companies that use AI. They're companies that can't exist without it.",
    "The blockchain doesn't lie. But the people building on it definitely can.",
    "Rate limiting isn't just about protecting servers — it's about protecting user experience.",
    "Hardware wallets look silly until you see another exchange freeze withdrawals.",
    "Tech mentorship compounds faster than any investment. Find a mentor. Be a mentor.",
    "The best monitoring alert is the one that fires before the user notices anything wrong.",
    "Crypto governance is just politics with more transparency and fewer voters.",
    "Latency is a feature killer. Shave 100ms and watch conversion rates climb.",
    "Building for scale you don't have yet is how startups die with beautiful architectures.",
    "The AI model you fine-tuned last month is already outdated. Welcome to the treadmill.",
    "In crypto, the community IS the product. Tokenomics is just the incentive layer.",
    "Developer tools that require a tutorial longer than 5 minutes have already lost.",
    "The most valuable skill in tech isn't coding — it's translating business problems into technical solutions.",
    "Rollups are doing the heavy lifting so Ethereum doesn't have to. Modular future is here.",
    "Good error handling is the difference between an app that crashes and an app that recovers gracefully.",
    "AI-assisted debugging is like having a senior engineer on call 24/7 who never gets tired.",
    "The next unicorn is probably being built by someone who's never been to a tech conference.",
    "Proof of stake isn't just an energy upgrade — it's a completely different security model.",
]

# Shuffle for variety in posting order
random.shuffle(TWEETS)


def seed():
    db = SessionLocal()
    try:
        existing = db.query(TweetQueue).filter(TweetQueue.status == "pending").count()
        print(f"Existing pending tweets: {existing}")

        added = 0
        for i, content in enumerate(TWEETS):
            # Check for duplicates
            exists = (
                db.query(TweetQueue)
                .filter(TweetQueue.content == content)
                .first()
            )
            if exists:
                continue

            tweet = TweetQueue(
                content=content,
                status="pending",
                priority=random.randint(0, 5),
            )
            db.add(tweet)
            added += 1

            if added % 50 == 0:
                db.commit()
                print(f"  Added {added} tweets...")

        db.commit()
        total = db.query(TweetQueue).filter(TweetQueue.status == "pending").count()
        print(f"Seeded {added} new tweets. Total pending: {total}")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
